server:
  port: 8007

spring:
  application:
    name: list-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.51:3306/dream?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dream
    password: 1234
  security:
    oauth2:
     resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.54:8080/auth/realms/MSA/protocol/openid-connect/certs

keycloak:
  realm: MSA
  bearer-only: true
  ssl-required: external
  resource: spring-gateway-client
  auth-server-url: http://192.168.1.54:8080/auth
  credentials:
    secret: WEcACPUTWPfuhPrEz3bBaHcl7OLLmYX1
   
mybatis:
#  configuration:
#    multiple-result-sets-enabled: false
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
#    jdbc-type-for-null: varchar
#    default-fetch-size: 500
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.dream.list.dto


#logging:
#  file:
#    name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
#    max-history: 7 # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
#    max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈이다.
##  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
##    com.project.study : error
##    com.project.study.controller : debug
    
eureka:
  instance:
    instance-id: list-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

         