server:
  port: 64412

spring.mvc.view.prefix: /WEB-INF/views/ 
spring.mvc.view.suffix: .jsp

spring:
  application:
    name: user-service
  devtools:
     livereload:
       enabled: true
     restart:
      enabled: true
      
eureka:
  instance:
    instance-id: user-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka